# file konfigurasi Monitor on
# Koreksi file konfigurasi jamon baris awal dan baris tengah ada tambahan 
# logika OR / "||" sedangkan baris akhir tidak ada
buat_pembataswaktuLebsam $menit45shubuh $pukulqomatShubuh || 
if [[ $nama_hari = Friday ]];then
    buat_pembataswaktuLebsam $menit45zhuhur $zhuhur || buat_pembataswaktuLebsam $pukulselesaijumatan $menit45ashar 
else 
    buat_pembataswaktuLebsam $menit45zhuhur $pukulqomatZhuhur || buat_pembataswaktuLebsam $pukulselesaishalatzhuhur $menit45ashar
fi ||
buat_pembataswaktuLebsam $menit45ashar $pukulqomatAshar || 
buat_pembataswaktuLebsam $menit45maghrib $pukulqomatMaghrib || 
buat_pembataswaktuLebsam $menit45isya $pukulqomatIsya
