# file konfigurasi Monitor on
# Koreksi file konfigurasi jamon baris awal dan baris tengah ada tambahan 
# "||" sedangkan baris akhir tidak ada
buat_pembataswaktuLebsam $menit45shubuh $pukulqomatShubuh || 
if [[ $nama_hari = Friday ]];then
    buat_pembataswaktuLebsam $menit45zhuhur $zhuhur || buat_pembataswaktuLebsam $pukulselesaijumatan $menit45ashar 
else 
    buat_pembataswaktuLebsam $menit45zhuhur $pukulqomatZhuhur || buat_pembataswaktuLebsam $pukulselesaishalatzhuhur $menit45ashar
fi ||
buat_pembataswaktuLebsam $menit45ashar $pukulqomatAshar || 
buat_pembataswaktuLebsam $menit45maghrib $pukulqomatMaghrib  || 
buat_pembataswaktuLebsam $pukulselesaishalatmaghrib $pukulqomatIsya || 
# monitor on dilanjutkan
buat_pembataswaktuLebsam $pukulselesaishalatshubuh $pukul_matahariterbit ||
buat_pembataswaktuLebsam $dhukha $menit45zhuhur ||
buat_pembataswaktuLebsam $pukulselesaishalatashar $menit45maghrib ||
buat_pembataswaktuLebsam $pukulselesaishalatmaghrib $menit45isya ||
buat_pembataswaktuLebsam $pukulselesaishalatisya 23:59

## buat on waktu 1 jam sebelum adzan hingga iqomah
#buat_pembataswaktuLebsam $menit45shubuh $pukulqomatShubuh || 
#if [[ $nama_hari = Friday ]];then
    #buat_pembataswaktuLebsam $menit45zhuhur $zhuhur
#else 
    #buat_pembataswaktuLebsam $menit45zhuhur $pukulqomatZhuhur
#fi ||
#buat_pembataswaktuLebsam $menit45ashar $pukulqomatAshar || 
#buat_pembataswaktuLebsam $menit45maghrib $pukulqomatMaghrib || 
#buat_pembataswaktuLebsam $pukulselesaishalatmaghrib $pukulqomatIsya
