# file konfigurasi Monitor off
# Koreksi file konfigurasi jamon baris awal dan baris tengah ada tambahan 
# "||" sedangkan baris akhir tidak ada
buat_pembataswaktuLebsam $pukulqomatShubuh $pukulselesaishalatshubuh ||
if [[ $nama_hari = Friday ]];then 
    buat_pembataswaktuLebsam $zhuhur $pukulselesaijumatan
else
    buat_pembataswaktuLebsam $pukulqomatZhuhur $pukulselesaishalatzhuhur
fi ||
buat_pembataswaktuLebsam $pukulqomatAshar $pukulselesaishalatashar ||
buat_pembataswaktuLebsam $pukulqomatMaghrib $pukulselesaishalatmaghrib ||
buat_pembataswaktuLebsam $pukulqomatIsya $pukulselesaishalatisya || 
buat_pembataswaktuLebsam 00:00 $menit45shubuh ||
buat_pembataswaktuLebsam $pukul_matahariterbit $dhukha

## buat off dari iqomah hingga 1 jam sebelum adzan
#buat_pembataswaktuLebsam $pukulqomatShubuh $menit45zhuhur ||
#if [[ $nama_hari = Friday ]];then 
    #buat_pembataswaktuLebsam $zhuhur $menit45ashar
#else
    #buat_pembataswaktuLebsam $pukulqomatZhuhur $menit45ashar
#fi ||
#buat_pembataswaktuLebsam $pukulqomatAshar $menit45maghrib ||
#buat_pembataswaktuLebsam $pukulqomatMaghrib $menit45isya ||
#buat_pembataswaktuLebsam $pukulqomatIsya 23:59 || 
#buat_pembataswaktuLebsam 00:00 $menit45shubuh
